console: true
org: tonyhsieh
app: aws-node-http-api-project
service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    DYNAMODB_MOJO_TABLE: ${self:service}-mojoTable-${sls:stage}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:Get*"
        - "dynamodb:Scan*"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
      Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-mojoTable-${sls:stage}

functions:
  getMojo: 
    handler: getMojo.getMojo
    events:
      - httpApi:
          path: /mojo/{id}
          method: get
  createMojo:
    handler: createMojo.createMojo
    events:
      - httpApi:
          path: /
          method: post
  getMojos:
    handler: getMojos.getMojos
    events: 
      - httpApi:
          path: /
          method: get
resources:
  Resources:
    MojoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: uuid
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: uuid
            KeyType: HASH
        TableName: ${self:service}-mojoTable-${sls:stage}
