console: true 
org: tonyhsieh
app: aws-api
service: aws-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  deploymentMethod: direct
  environment:
    DYNAMODB_MOJO_TABLE: ${self:service}-mojoTable-${sls:stage}
    DYNAMODB_WHITELIST_TABLE: ${self:service}-whitelistTable-${sls:stage}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:Get*"
        - "dynamodb:Scan*"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
      Resource: 
        - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-mojoTable-${sls:stage}
        - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-whitelistTable-${sls:stage}

package:
  excludeDevDependencies: true  
  exclude:
    - node_modules/**
    - venv/**

functions:
  getMojo: 
    handler: getMojo.getMojo
    events:
      - httpApi:
          path: /mojo/metadata/{id}
          method: get
  getMojoSeed: 
    handler: mojoSeed.getMojoSeed
    events:
      - httpApi:
          path: /moj-seed/metadata/{id}
          method: get
  sproutMojoSeed:
    handler: mojoSeed.sproutMojoSeed
    events:
      - httpApi:
          path: /moj-seed/action/sprout/{id}
          method: put 
  claimMojoSeed: 
    handler: mojoSeed.claimMojoSeed
    events:
      - httpApi:
          path: /moj-seed/action/claim/{addr}
          method: get
  getMojos: 
    handler: getMojos.getMojos
    events:
      - httpApi:
          path: /mojos
          method: get


resources:
  Resources:
    MojoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: uuid
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: uuid
            KeyType: HASH
        TableName: ${self:service}-mojoTable-${sls:stage}
    WhitelistTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: walletKey
            AttributeType: S
          - AttributeName: saleKey
            AttributeType: S
          - AttributeName: walletOrder
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: walletKey
            KeyType: HASH
          - AttributeName: saleKey
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: saleKey-index
            KeySchema:
            - AttributeName: saleKey
              KeyType: HASH
            - AttributeName: walletOrder
              KeyType: RANGE
            Projection:
              ProjectionType: INCLUDE
              NonKeyAttributes:
                - walletId
        TableName: ${self:service}-whitelistTable-${sls:stage}

plugins:
  - serverless-offline
  - serverless-plugin-include-dependencies
  - serverless-dotenv-plugin
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    exclude: 'aws-sdk'
    target: node14
    define:
      'require.resolve': undefined
    platform: node
    concurrency: 10
